import { Zap, Shield, Building2 } from 'lucide-react';

export const PLANS = [
  {
    key: 'basic',
    name: 'Basic',
    price: 16,
    priceLabel: '$16/mo',
    icon: Zap,
    color: 'text-blue-500',
    border: 'border-blue-200',
    bg: 'bg-blue-50',
    description: 'Owner-operators / tiny fleets',
    bestFor: 'Solo operators or small 2-3 person teams starting out',
    features: [
      'Up to 3 drivers & 3 trucks',
      'Load tracking',
      'Invoicing',
      'Company & driver directory',
      'Document uploads',
    ],
  },
  {
    key: 'professional',
    name: 'Professional',
    price: 49,
    priceLabel: '$49/mo',
    icon: Shield,
    color: 'text-primary',
    border: 'border-primary/30',
    bg: 'bg-primary/5',
    description: 'Small trucking companies',
    popular: true,
    bestFor: 'Growing companies with 5-10 vehicles and dedicated payroll needs',
    includedFrom: 'Basic',
    features: [
      'Up to 10 drivers & 10 trucks',
      'Driver pay statements',
      'Fuel card imports',
      'Duplicate load detection',
      'Audit log',
    ],
  },
  {
    key: 'enterprise',
    name: 'Enterprise',
    price: 99,
    priceLabel: '$99/mo',
    icon: Building2,
    color: 'text-amber-500',
    border: 'border-amber-200',
    bg: 'bg-amber-50',
    description: 'Growing companies',
    bestFor: 'Established fleets wanting advanced analytics and automation',
    includedFrom: 'Professional',
    features: [
      'Unlimited drivers & trucks',
      'OCR document scanning',
      'Advanced reports',
      'Priority support',
      'Cloud backup & updates included',
    ],
  },
  {
    key: 'lifetime',
    name: 'Lifetime',
    price: 199,
    priceLabel: '$199 one-time',
    oneTime: true,
    icon: Shield,
    color: 'text-emerald-500',
    border: 'border-emerald-200',
    bg: 'bg-emerald-50',
    description: 'Pay once, use forever',
    bestFor: 'Owners who want to avoid recurring charges and get everything forever',
    includedFrom: 'Enterprise',
    features: [
      'All future features & updates',
      'Lifetime priority support',
    ],
  },
];