import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { useSession } from '@/components/shared/AppSession';
import PageHeader from '@/components/shared/PageHeader';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Printer, FileSpreadsheet } from 'lucide-react';

const YEARS = [2026, 2025, 2024, 2023];

function print1099(driver, company, year, totals) {
  const w = window.open('', '_blank');
  w.document.write(`
    <html><head><title>1099-NEC ${year} — ${driver.driver_name}</title>
    <style>
      body { font-family: Arial, sans-serif; font-size: 11px; margin: 40px; color: #000; }
      h1 { font-size: 16px; margin-bottom: 4px; }
      .subtitle { color: #555; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; }
      th { background: #f5f5f5; font-weight: 600; }
      .box { border: 2px solid #000; padding: 12px; margin-top: 20px; max-width: 480px; }
      .label { font-size: 9px; color: #666; text-transform: uppercase; }
      .value { font-size: 14px; font-weight: bold; margin-top: 2px; }
      @media print { body { margin: 20px; } }
    </style></head><body>
    <h1>Form 1099-NEC — ${year}</h1>
    <div class="subtitle">Nonemployee Compensation</div>
    <div class="box">
      <div class="label">Payer (Company)</div>
      <div class="value">${company?.company_name || 'Your Company'}</div>
      ${company?.address_1 ? `<div>${company.address_1}</div>` : ''}
      ${company?.city ? `<div>${company.city}, ${company.state || ''} ${company.zip || ''}</div>` : ''}
    </div>
    <div class="box" style="margin-top:12px;">
      <div class="label">Recipient (Driver)</div>
      <div class="value">${driver.driver_name}</div>
    </div>
    <table style="margin-top:24px;">
      <tr><th>Box 1 — Nonemployee Compensation</th><td style="font-size:16px;font-weight:bold;">$${totals.gross.toLocaleString(undefined,{minimumFractionDigits:2})}</td></tr>
      <tr><th>Total Deductions (reference only)</th><td>$${totals.deductions.toLocaleString(undefined,{minimumFractionDigits:2})}</td></tr>
      <tr><th>Net Paid (reference only)</th><td>$${totals.net.toLocaleString(undefined,{minimumFractionDigits:2})}</td></tr>
      <tr><th>Tax Year</th><td>${year}</td></tr>
    </table>
    <p style="margin-top:24px;color:#888;font-size:10px;">This is a reference document generated by TruckOps. Consult your accountant before filing official IRS forms.</p>
    <script>window.onload=()=>window.print();</script>
    </body></html>
  `);
  w.document.close();
}

export default function Taxes1099() {
  const { session } = useSession();
  const tenantId = session?.tenant_id;
  const currentYear = new Date().getFullYear();
  const [year, setYear] = useState(String(currentYear));

  const { data: statements = [], isLoading } = useQuery({
    queryKey: ['statements-1099', tenantId],
    queryFn: () => tenantId
      ? base44.entities.DriverStatement.filter({ tenant_id: tenantId, published: true }, '-statement_date', 500)
      : Promise.resolve([]),
    enabled: !!tenantId,
  });

  const { data: carrierCompany = [] } = useQuery({
    queryKey: ['settings-company', tenantId],
    queryFn: () => tenantId ? base44.entities.Company.filter({ company_type: 'carrier', tenant_id: tenantId }, '-created_date', 1) : Promise.resolve([]),
    enabled: !!tenantId,
  });

  const yearStatements = useMemo(() =>
    statements.filter(s => s.statement_date?.startsWith(year) || s.period_start?.startsWith(year)),
    [statements, year]
  );

  const byDriver = useMemo(() => {
    const map = {};
    yearStatements.forEach(s => {
      const key = s.driver_id || s.driver_name;
      if (!map[key]) map[key] = { driver_name: s.driver_name, driver_id: s.driver_id, gross: 0, deductions: 0, fuel: 0, net: 0, count: 0 };
      map[key].gross += s.gross_total || 0;
      map[key].deductions += s.deductions_total || 0;
      map[key].fuel += s.fuel_total || 0;
      map[key].net += s.final_check_amount || 0;
      map[key].count++;
    });
    return Object.values(map).sort((a, b) => a.driver_name?.localeCompare(b.driver_name));
  }, [yearStatements]);

  const company = carrierCompany[0] || null;

  return (
    <div className="p-4 space-y-4">
      <PageHeader
        title="1099s"
        description={`${byDriver.length} driver${byDriver.length !== 1 ? 's' : ''} with earnings in ${year}`}
        actions={
          <Select value={year} onValueChange={setYear}>
            <SelectTrigger className="h-8 text-xs w-28">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {YEARS.map(y => <SelectItem key={y} value={String(y)}>{y}</SelectItem>)}
            </SelectContent>
          </Select>
        }
      />

      {isLoading ? (
        <div className="text-center py-16 text-muted-foreground text-sm">Loading statements…</div>
      ) : byDriver.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-24 text-muted-foreground">
          <FileSpreadsheet className="w-10 h-10 mb-3 opacity-30" />
          <p className="text-sm font-medium">No published statements found for {year}.</p>
          <p className="text-xs mt-1">Publish driver statements to see 1099 totals here.</p>
        </div>
      ) : (
        <div className="border border-border rounded-lg overflow-hidden">
          <table className="w-full text-xs">
            <thead className="bg-muted/40 border-b border-border">
              <tr>
                <th className="text-left px-4 py-3 font-semibold text-muted-foreground">Driver</th>
                <th className="text-left px-4 py-3 font-semibold text-muted-foreground">Statements</th>
                <th className="text-right px-4 py-3 font-semibold text-muted-foreground">Gross Earnings</th>
                <th className="text-right px-4 py-3 font-semibold text-muted-foreground">Deductions</th>
                <th className="text-right px-4 py-3 font-semibold text-muted-foreground">Fuel Deducted</th>
                <th className="text-right px-4 py-3 font-semibold text-muted-foreground">Net Paid</th>
                <th className="px-4 py-3"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {byDriver.map(d => (
                <tr key={d.driver_id || d.driver_name} className="hover:bg-muted/20 transition-colors">
                  <td className="px-4 py-3 font-medium">{d.driver_name || '—'}</td>
                  <td className="px-4 py-3 text-muted-foreground">{d.count}</td>
                  <td className="px-4 py-3 text-right text-green-600 font-medium">
                    ${d.gross.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </td>
                  <td className="px-4 py-3 text-right text-red-500">
                    -${d.deductions.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </td>
                  <td className="px-4 py-3 text-right text-orange-500">
                    -${d.fuel.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </td>
                  <td className="px-4 py-3 text-right font-bold">
                    ${d.net.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <Button
                      variant="outline" size="sm" className="h-7 text-xs gap-1"
                      onClick={() => print1099(d, company, year, { gross: d.gross, deductions: d.deductions + d.fuel, net: d.net })}
                    >
                      <Printer className="w-3 h-3" /> 1099-NEC
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
            <tfoot className="border-t-2 border-border bg-muted/30">
              <tr>
                <td colSpan={2} className="px-4 py-3 font-semibold text-xs">TOTALS</td>
                <td className="px-4 py-3 text-right text-green-600 font-bold text-xs">
                  ${byDriver.reduce((s, d) => s + d.gross, 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                </td>
                <td className="px-4 py-3 text-right text-red-500 font-bold text-xs">
                  -${byDriver.reduce((s, d) => s + d.deductions, 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                </td>
                <td className="px-4 py-3 text-right text-orange-500 font-bold text-xs">
                  -${byDriver.reduce((s, d) => s + d.fuel, 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                </td>
                <td className="px-4 py-3 text-right font-bold text-xs">
                  ${byDriver.reduce((s, d) => s + d.net, 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                </td>
                <td />
              </tr>
            </tfoot>
          </table>
        </div>
      )}
    </div>
  );
}